# Generated by Django 4.2.4 on 2023-10-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journalentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='analysed_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_analysed',
            field=models.BooleanField(default=False),
        ),
    ]
