# Generated by Django 4.2.4 on 2023-10-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlabel',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
