# Generated by Django 4.2.4 on 2023-10-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_emotionlabel_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionlabel',
            name='entries',
        ),
        migrations.AlterField(
            model_name='emotionlabel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emotionlabel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
